### ISSUE TITLE
 certificate signed by unknown authority

### ISSUE THREAD

**Issue by acarsercan** [jgriff/k8s-resource#14]
Hi,

Any chance of skipping ssl verification for k8s ca?

Regards

**Comment by jgriff** [comment]
Seems easily doable.  We would just add another config option:
* `skip_ssl_verification`: _Optional_.  Value either `true`|`false`.  Adds `--insecure-skip-tls-verify={value}` to the value configured for all `kubectl` invocations.

You closed this, did you find a different solution?

**Comment by acarsercan** [comment]
Apologies I should of replied before closing.

I was passing base64 certificate via vault rather than PEM.

I don't think we need any new flags
________________________________
